export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGIN_RESET = 'LOGIN_RESET'

export const CONFIRM_REQUEST = 'CONFIRM_REQUEST'
export const CONFIRM_SUCCESS = 'CONFIRM_SUCCESS'
export const CONFIRM_FAIL = 'CONFIRM_FAIL'
export const CONFIRM_RESET = 'CONFIRM_FAIL'

export const SELECTION_GET = 'SELECTION_GET'
export const SELECTION_SET = 'SELECTION_SET'
export const SELECTION_RESET = 'SELECTION_RESET'
export const SELECTION_FAIL = 'SELECTION_FAIL'

export const SUBMIT_REQUEST = 'SUBMIT_REQUEST'
export const SUBMIT_SUCCESS = 'SUBMIT_SUCCESS'
export const SUBMIT_FAIL = 'SUBMIT_FAIL'
export const SUBMIT_RESET = 'SUBMIT_RESET'

export const REPORT_ALL_ZONE_REQUEST = 'REPORT_ALL_ZONE_REQUEST'
export const REPORT_ALL_ZONE_SUCCESS = 'REPORT_ALL_ZONE_SUCCESS'
export const REPORT_ALL_ZONE_FAIL = 'REPORT_ALL_ZONE_FAIL'

export const REPORT_ONE_ZONE_REQUEST = 'REPORT_ONE_ZONE_REQUEST'
export const REPORT_ONE_ZONE_SUCCESS = 'REPORT_ONE_ZONE_SUCCESS'
export const REPORT_ONE_ZONE_FAIL = 'REPORT_ONE_ZONE_FAIL'

export const REPORT_ONE_CANDIDA_REQUEST = 'REPORT_ONE_CANDIDA_REQUEST'
export const REPORT_ONE_CANDIDA_SUCCESS = 'REPORT_ONE_CANDIDA_SUCCESS'
export const REPORT_ONE_CANDIDA_FAIL = 'REPORT_ONE_CANDIDA_FAIL'