# Generated by Django 4.0 on 2022-10-26 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidas',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('family', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=10)),
                ('prs', models.IntegerField()),
                ('zone', models.IntegerField()),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='candidas/')),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('family', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=10)),
                ('prs', models.IntegerField()),
                ('zone', models.IntegerField()),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Votes',
            fields=[
                ('created', models.DateField(auto_now_add=True)),
                ('ip', models.CharField(blank=True, max_length=100)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('candida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.candidas')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.members')),
            ],
        ),
    ]
