# Generated by Django 3.2.16 on 2022-10-26 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='voted',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
