# Generated by Django 3.2.16 on 2022-10-26 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_members_voted'),
    ]

    operations = [
        migrations.AddField(
            model_name='votes',
            name='zone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
