# Generated by Django 3.2.16 on 2022-10-26 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20221026_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votes',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
