# Generated by Django 4.0.8 on 2022-10-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_phone_members_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMS',
            fields=[
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('password', models.CharField(blank=True, max_length=20, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
